### ISSUE TITLE
Multiple Query Parameters

### ISSUE THREAD

**Issue by ealanhill** [DroidsOnRoids/mockwebserver-path-dispatcher#16]
So far, this library looks exactly like what I'm looking for when testing MockWebserver.

I have run into a problem with a request that has multiple query parameters.

For example:

```Kotlin
@Before
fun onBefore() {
   val dispatcher = FixtureDispatcher()
   val factory = PathQueryConditionFactory()
   dispatcher.putResponse(factory.withPathSuffixAndQueryParameter("/some/suffix?parameter1=x", "parameter2", "y"), "mapped")
   mockWebServer.start(8080)
   mockWebServer.dispatcher = dispatcher
```

this causes an exception to be thrown by the mockwebserver:

```
E/MockWebServer: MockWebServer[8080] connection from /127.0.0.1 crashed
    java.lang.IllegalArgumentException: Unexpected request: GET /some/suffic?parameter1=x&parameter2=y HTTP/1.1
        at pl.droidsonroids.testing.mockwebserver.FixtureDispatcher.dispatch(FixtureDispatcher.kt:47)
        at okhttp3.mockwebserver.MockWebServer$SocketHandler.processOneRequest(MockWebServer.kt:593)
        at okhttp3.mockwebserver.MockWebServer$SocketHandler.handle(MockWebServer.kt:551)
        at okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1.run(Util.kt:556)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

It would be nice to be able to pass in a query map (like Retrofit). Are there plans for this?

**Comment by koral--** [comment]
No plans for feature like that.
For now you can use `HttpUrlCondition` to achieve that.
See one before last snippet in readme: https://github.com/DroidsOnRoids/mockwebserver-path-dispatcher#example
