### ISSUE TITLE
How to specify a null body for a 204 response?

### ISSUE THREAD

**Issue by free5ty1e** [DroidsOnRoids/mockwebserver-path-dispatcher#19]
My YAML file for my 204 response is as follows:

```
statusCode : 204
```

I get the following exception during testing this:

```
03-18 17:59:04.679 12529-12660/com.iwsinc.gmi.test E/MockWebServer: MockWebServer[50000] connection from /127.0.0.1 crashed
    java.lang.IllegalArgumentException: Invalid path: fixtures/null
        at pl.droidsonroids.testing.mockwebserver.StringUtils.getResourceAsString(StringExtensions.kt:7)
        at pl.droidsonroids.testing.mockwebserver.YamlResourcesParser.parseFrom(YamlResourcesParser.kt:18)
        at pl.droidsonroids.testing.mockwebserver.MockResponseBuilder.buildMockResponse(MockResponseBuilder.kt:9)
        at pl.droidsonroids.testing.mockwebserver.FixtureDispatcher.dispatch(FixtureDispatcher.kt:44)
        at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:573)
        at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:531)
        at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:456)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

...If I attempt to define an empty body with my YAML like this:
```
statusCode : 204
headers:
  - 'Content-Type: application/json; charset=utf-8'
body: >
 {}
```

... then I get this exception instead:

```
java.net.ProtocolException: HTTP 204 had non-zero Content-Length: 2
```

How do I define a simple `204` response with an empty body to satisfy HTTP protocol here, any ideas?

My dispatcher definition line for this particular response is as follows:

```
    dispatcher.putResponse(pathQueryConditionFactory.withPathSuffix("/endpoint"), "yaml_file")

```

Thank you for any insights or suggestions!

**Comment by koral--** [comment]
Indeed it is not supported for now. I'll add it.
Thanks for the report.

**Comment by koral--** [comment]
Version 1.1.2 has just been released.
For responses with code 204 you can just omit body like in this test: https://github.com/DroidsOnRoids/mockwebserver-path-dispatcher/blob/develop/dispatcher/src/test/resources/fixtures/no_body.yaml
